/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
const MASKED_STRING = '******';
const REPLACE_TYPE_MATCH_ONLY = 'MATCH_ONLY';
const REPLACE_TYPE_ALL_MESSAGE = 'ALL_MESSAGE';
const PATTERN_TYPE_CREDIT_CARD = 'CREDIT_CARD_PATTERN';
const PATTERN_TYPE_DEFAULT = 'DEFAULT_PATTERN';

const pathsToMask = [
  'config.liveperson.password',
  'config.livepersonasync.password',
  'config.livepersonasync.api.secret',
  'config.livepersonasync.api.tokenSecret',
  'config.wva.clientSecret',
  'config.wcs.password',
  'config.suggestEntities.password',
  'config.toneAnalyzer.password',
  'config.redis.uri_cli',
  'config.redis.uri',
  'config.redis.password',
  'config.redis.key',
  'config.redis.hmacKey',
  'config.otac.appId',
  'config.vftil',
  'config.gateway',
  'config.gatewayClient.auth.secret',
  'config.conversationLoggerWare.uri',
  'config.metrics.apikey',
  'config.ibmCloudEventsService.name',
  'config.ibmCloudEventsService.password',
  'opts.clientSecret',
  'error.options.body.password',
  'options.body.password',
  'body.password',
  'password',
  'options.auth.bearer',
  'auth.bearer',
  'update.session',
  'err.passphrase',
  'err.options.passphrase',
  'err.options.pfx',
  'appKey',
  'secret',
  'accessToken',
  'accessTokenSecret',
  'update.customerId',
  'update.customerName',
  'update.toneAnalysis',
  'update.private',
  'config.password',
  'config.service',
  'profileResp',
  'headers.Authorization',
  'message.text',
  'tree',
  'body.message.text',
  'message.message.text',
  'text',
  'update.message.text',
  'update.messages',
  'params.context.profile',
  'params.context.accessToken',
  'params.context.private',
  'params.context.credentials',
  'params.context.workdayTransfer',
  'params.context.changeJobRequest',
  'params.context.workdayTransferToShow',
  'params.context.workdaySearch',
  'params.context.webhook',
  'params.context.workday',
  'params.context.resultData',
  'params.context.personId',
  'params.context.addressUpdate',
  'params.context.personCollectionId',
  'params.input.text',
  'params.message',
  'waRequest.context.profile',
  'waRequest.context.accessToken',
  'waRequest.context.private',
  'waRequest.context.credentials',
  'waRequest.context.workdayTransfer',
  'waRequest.context.changeJobRequest',
  'waRequest.context.workdayTransferToShow',
  'waRequest.context.workdaySearch',
  'waRequest.context.webhook',
  'waRequest.context.workday',
  'waRequest.context.resultData',
  'waRequest.context.personId',
  'waRequest.context.personCollectionId',
  'waRequest.context.addressUpdate',
  'waRequest.input.text',
  'waRequest.message',
  'waResponse.context.profile',
  'waResponse.context.accessToken',
  'waResponse.context.credentials',
  'waResponse.context.private',
  'waResponse.context.workdayTransfer',
  'waResponse.context.changeJobRequest',
  'waResponse.context.workdayTransferToShow',
  'waResponse.context.workdaySearch',
  'waResponse.context.webhook',
  'waResponse.context.workday',
  'waResponse.context.resultData',
  'waResponse.context.personId',
  'waResponse.context.personCollectionId',
  'waResponse.context.addressUpdate',
  'waResponse.input.text',
  'waResponse.message',
  'workday',
  'message',
  'result',
];

const pathsToMaskMatchOnly = ['message.value.message.text', 'data.text', 'concatenated', 'attachment.attachments'];

module.exports = {
  pathsToMask,
  pathsToMaskMatchOnly,
  MASKED_STRING,
  REPLACE_TYPE_ALL_MESSAGE,
  REPLACE_TYPE_MATCH_ONLY,
  PATTERN_TYPE_CREDIT_CARD,
  PATTERN_TYPE_DEFAULT,
};
