/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
export const ENUMERATIONS_CHART_TYPE = {
  CATALOG_RULES_FREQUENCY: 'BAR_CATALOG_RULES_FREQUENCY',
  CLASSIFICATION_RULES_FREQUENCY: 'CLASSIFICATION_RULES_FREQUENCY',
  BUY_RULES_FREQUENCY: 'BUY_RULES_FREQUENCY',
  TOTAL_VALIDATION_COUNT: 'TOTAL_VALIDATION_COUNT',
}
