/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  CarbonModule,
	FadeModule,
  DownloadModule,
  EditModule,
  ManageProtectionModule,
  SysProvisionModule,
  AppsModule,
  UserAvatarModule,
  SettingsModule,
  CatalogModule,
  SkillLevelModule,
  ChartBarModule,
  Data_1Module,
  DashboardModule,
  CategoryNewEachModule,
  ReportModule,
  ChatModule,
  AddModule,
  FilterModule,
  InformationModule,
  ViewModule,
  ViewOffModule,
  ShoppingCatalogModule,
  WorkspaceImportModule,
  FunctionModule,
  ActivityModule,
  ResetModule,
} from "@carbon/icons-angular";

import {
  ButtonModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InputModule,
  GridModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  TabsModule,
  TilesModule,
  FileUploaderModule,
  IconModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    // -> carbon-icons-angular
    CarbonModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    AppsModule,
    UserAvatarModule,
    SettingsModule,
    CatalogModule,
    SkillLevelModule,
    ChartBarModule,
    Data_1Module,
    DashboardModule,
    CategoryNewEachModule,
    ReportModule,
    ChatModule,
    AddModule,
    FilterModule,
    InformationModule,
    ViewModule,
    ViewOffModule,
    ShoppingCatalogModule,
    WorkspaceImportModule,
    FunctionModule,
    ActivityModule,
    ResetModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    TilesModule,
    FileUploaderModule,
    IconModule,
  ],
  exports: [
    // -> carbon-icons-angular
    CarbonModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    AppsModule,
    UserAvatarModule,
    SettingsModule,
    CatalogModule,
    SkillLevelModule,
    ChartBarModule,
    Data_1Module,
    DashboardModule,
    CategoryNewEachModule,
    ReportModule,
    ChatModule,
    AddModule,
    FilterModule,
    InformationModule,
    ViewModule,
    ViewOffModule,
    ShoppingCatalogModule,
    WorkspaceImportModule,
    FunctionModule,
    ActivityModule,
    ResetModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    TilesModule,
    FileUploaderModule,
    IconModule,
  ]
})
export class CarbonFrameworkModule {}
