/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  CarbonModule,
  FadeModule,
  DownloadModule,
  EditModule,
  ManageProtectionModule,
  SysProvisionModule,
  AppsModule,
  UserAvatarModule,
  SettingsModule,
  CatalogModule,
  SkillLevelModule,
  ChartBarModule,
  Data_1Module,
  DashboardModule,
  CategoryNewEachModule,
  UserSpeakerModule,
  ReportModule,
  ChatModule,
  AddModule,
  FilterModule,
  InformationModule,
  BuildingModule,
  RuleModule,
  DocumentImportModule,
  FunctionModule,
  MailReplyModule,
  ErrorFilledModule,
  CloseFilledModule,
} from '@carbon/icons-angular';

import {
  ButtonModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  DialogModule,
  ProgressIndicatorModule,
  FileUploaderModule,
  IconModule,
  ComboBoxModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    // -> carbon-icons-angular
    CarbonModule,
    FadeModule,
    DownloadModule,
    EditModule,
    ManageProtectionModule,
    SysProvisionModule,
    AppsModule,
    UserAvatarModule,
    SettingsModule,
    CatalogModule,
    SkillLevelModule,
    ChartBarModule,
    Data_1Module,
    DashboardModule,
    CategoryNewEachModule,
    UserSpeakerModule,
    ReportModule,
    ChatModule,
    AddModule,
    FilterModule,
    InformationModule,
    BuildingModule,
    RuleModule,
    DocumentImportModule,
    FunctionModule,
    MailReplyModule,
    ErrorFilledModule,
    CloseFilledModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    DialogModule,
    ProgressIndicatorModule,
    FileUploaderModule,
    IconModule,
    ComboBoxModule,
  ],
  exports: [
    // -> carbon-icons-angular
    CarbonModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    AppsModule,
    UserAvatarModule,
    SettingsModule,
    CatalogModule,
    DocumentImportModule,
    SkillLevelModule,
    ChartBarModule,
    Data_1Module,
    DashboardModule,
    CategoryNewEachModule,
    UserSpeakerModule,
    ReportModule,
    ChatModule,
    AddModule,
    FilterModule,
    InformationModule,
    BuildingModule,
    RuleModule,
    FunctionModule,
    MailReplyModule,
    ErrorFilledModule,
    CloseFilledModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    DialogModule,
    ProgressIndicatorModule,
    FileUploaderModule,
    IconModule,
    ComboBoxModule,
  ]
})
export class CarbonFrameworkModule {}
