apiVersion: v1
kind: Service
metadata:
  name: {{ template "app.fullname" . }}
  labels:
    app: {{ template "app.fullname" . }}
    chart: "{{ template "isaidt.chart" . }}"
    release: "{{ .Release.Name }}"
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: bot-port
  selector:
    app: {{ template "app.fullname" . }}
