/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
export enum EVENT_TYPE {
  // CHAT_WINDOW_MANIPULATION
  OPEN_CHAT_WINDOW = "OPEN_CHAT_WINDOW",
  CLOSE_CHAT_WINDOW = "CLOSE_CHAT_WINDOW",
  MINIMIZE_CHAT_WINDOW = "MINIMIZE_CHAT_WINDOW",
  EXPAND_CHAT_WINDOW = "EXPAND_CHAT_WINDOW",
  TOGGLE_CHAT_WINDOW_EXPANSION = "TOGGLE_CHAT_WINDOW_EXPANSION",
  MOVE_CHAT_WINDOW = "MOVE_CHAT_WINDOW",
  MINIMIZE_LEFT_PANEL = "MINIMIZE_LEFT_PANEL",
  EXPAND_LEFT_PANEL = "EXPAND_LEFT_PANEL",
  TOGGLE_LEFT_PANEL = "TOGGLE_LEFT_PANEL",
  MINIMIZE_RIGHT_PANEL = "MINIMIZE_RIGHT_PANEL",
  EXPAND_RIGHT_PANEL = "EXPAND_RIGHT_PANEL",
  TOGGLE_RIGHT_PANEL = "TOGGLE_RIGHT_PANEL",
  IS_AUDIO_MESSAGE_PLAYING = "IS_AUDIO_MESSAGE_PLAYING",
  CHAT_ZOOM = "CHAT_ZOOM",
  // WBCS
  CHANGE_BASE_WBC = "CHANGE_BASE_WBC",
  CHANGE_HEADER_WBC = "CHANGE_HEADER_WBC",
  CHANGE_LEFT_PANEL_WBC = "CHANGE_LEFT_PANEL_WBC",
  CHANGE_RIGHT_PANEL_WBC = "CHANGE_RIGHT_PANEL_WBC",
  CHANGE_SIDE_NAV_WBC = "CHANGE_SIDE_NAV_WBC",
  WBC_MUTE = "WBC_MUTE",
  WBC_HEADER_INITIALIZED = "WBC_HEADER_INITIALIZED",
  // MESSAGES
  MESSAGE_RECEIVED = "MESSAGE_RECEIVED",
  AUDIO_MESSAGE_RECEIVED = "AUDIO_MESSAGE_RECEIVED",
  SEND_MESSAGE = "SEND_MESSAGE",
  LOAD_MESSAGES = "LOAD_MESSAGES",
  SEND_AUDIO_MESSAGE = "SEND_AUDIO_MESSAGE",

  SESSION_CHANGE = "SESSION_CHANGE",
  LOAD_SESSION = "LOAD_SESSION",
  LANGUAGE_CHANGE = "LANGUAGE_CHANGE",
  OPEN_QUICK_LINK = "OPEN_QUICK_LINK",

  // MODAL
  OPEN_MODAL = "OPEN_MODAL",
  CLOSE_MODAL = "CLOSE_MODAL",
  SHOW_SURVEY_MODAL = "SHOW_SURVEY_MODAL",
  TEST_CASE_SHOW = "TEST_CASE_SHOW",
  OPEN_CONTENT_MODAL = "OPEN_CONTENT_MODAL",

}
