/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  ButtonModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ComboBoxModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InputModule,
  GridModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  StructuredListModule,
  AccordionModule,
  TabsModule,
  TilesModule,
  TagModule,
  FileUploaderModule,
  BreadcrumbModule,
  IconModule,
  SkeletonModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    ButtonModule,
    IconModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ComboBoxModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    TilesModule,
    TagModule,
    StructuredListModule,
    AccordionModule,
    FileUploaderModule,
    BreadcrumbModule,
    SkeletonModule,
  ],
  exports: [
    ButtonModule,
    IconModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ComboBoxModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    TilesModule,
    TagModule,
    StructuredListModule,
    AccordionModule,
    FileUploaderModule,
    BreadcrumbModule,
    SkeletonModule,
  ],
})
export class CarbonFrameworkModule { }
