/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  ButtonModule,
  NotificationModule,
  TilesModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InputModule,
  GridModule,
  BreadcrumbModule,
  SliderModule,
  LoadingModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  TabsModule,
  StructuredListModule,
  TagModule,
  FileUploaderModule,
  PlaceholderModule,
  ProgressIndicatorModule,
  ComboBoxModule,
  AccordionModule,
  InlineLoadingModule, 
  CodeSnippetModule,
  IconModule,
} from 'carbon-components-angular';

import {
  RenewModule
} from '@carbon/icons-angular'

@NgModule({
  imports: [
    ButtonModule,
    NotificationModule,
    TilesModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    BreadcrumbModule,
    SliderModule,
    LoadingModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    FileUploaderModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    ComboBoxModule,
    AccordionModule,
    InlineLoadingModule, 
    CodeSnippetModule,
    IconModule,
  ],
  exports: [
    ButtonModule,
    NotificationModule,
    TilesModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    BreadcrumbModule,
    SliderModule,
    LoadingModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    FileUploaderModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    ComboBoxModule,
    AccordionModule,
    InlineLoadingModule, 
    CodeSnippetModule,
    IconModule,
  ]
})
export class CarbonFrameworkModule { }
