/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
export const ACTION_ITEM_STATUSES = {
  PUBLISHED: 'PUBLISHED',
  REPUBLISHED: 'REPUBLISHED',
  ARCHIVED: 'ARCHIVED',
  COMPLETE: 'COMPLETED',
  COMPLETE_BY_SELLER: 'ACTIONED',
};

export const ACTION_ITEM_TYPE = 'ACTION_ITEM';

export const ACTION_ITEM_ACTION_STATUSES = {
  NEEDS_ACTION: 'NEEDS ACTION',
  REMEDIATED: 'REMEDIATED',
  NO_ACTION: 'NO ACTION',
}
