/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
export const ENUM_LIVE_METRIC_ID = {
  CONVERSATIONS_V1: 'conversationsV1',
  CONV_DURATION_AVG_IN_MINUTES_V1: 'conversationDurationAvgInMinutesV1',
  TRANSFERS_TO_AGENT_V1: 'transfersToAgentV1',
  MESSAGES_PER_CONVERSATION_AVG_COUNT_V1: 'messagesPerConversationAvgCountV1',
  MESSAGES_V1: 'messagesV1',
  CONVERSATIONS_WITH_USER_INTERACTION_V1: 'conversationsWithUserInteractionV1',
  CONVERSATIONS_WITHOUT_USER_INTERACTION_V1: 'conversationsWithoutUserInteractionV1',
  TOP_INTENTS_V1: 'topIntentsV1',
  TOP_INTENTS_WITH_FEEDBACK_V1: 'topIntentsWithFeedbackV1',
  LOW_CONFIDENCE_INTENTS_V1: 'lowConfidenceIntentsV1',
  LAST_INTENT_BEFORE_TRANSFER_V1: 'lastIntentBeforeTransferV1',
  UTTERANCES_BY_SKILL_V1: 'utterancesBySkillV1',
  CONVERSATIONS_V2: 'conversationsV2',
  USERS_V1: 'usersV1',
  USERS_NEW_V1: 'usersNewV1',
  USERS_RETURNING_V1: 'usersReturningV1',
  USERS_FROM_LANDING_PAGE_V1: 'usersFromLandingPageV1',
  USERS_FROM_S2P_PAGE_V1: 'usersFromS2PPageV1',
  USERS_FROM_SLACK_V1: 'usersFromSlackV1',
  USERS_TOTAL_REQUESTERS_V1: 'usersTotalRequestersV1',
  USERS_TOTAL_BUYERS_V1: 'userTotalBuyersV1',
  USERS_TOTAL_SUPPLIERS_V1: 'userTotalSuppliersV1',
  SURVEYS_POSITIVE_V1: 'surveysPositiveV1',
  SURVEYS_POSITIVE_TARGET_V1: 'surveysPositiveTargetV1',
  FEEDBACKS_POSITIVE_V1: 'feedbacksPositiveV1',
  FEEDBACKS_POSITIVE_TARGET_V1: 'feedbacksPositiveTargetV1',
  RESPONSE_CONFIDENCE_V1: 'responseConfidenceV1',
  RESPONSE_CONFIDENCE_TARGET_V1: 'responseConfidenceTargetV1',
  USAGE_BY_COUNTRY_V1: 'usageByCountryV1',
  USAGE_BY_GROUP_TRANSFER_TO_AGENT_V1: 'usageByGroupTransferToAgentV1',
  USAGE_BY_GROUP_GOODS_REQUESTS_V1: 'usageByGroupGoodsRequestsV1',
  USAGE_BY_GROUP_ACCOUNTING_V1: 'usageByGroupAccountingV1',
  USAGE_BY_GROUP_APPROVER_FLOW_V1: 'usageByGroupApproverFlowV1',
  USAGE_BY_GROUP_ERROR_MESSAGE_V1: 'usageByGroupErrorMessageV1',
  USAGE_BY_GROUP_BUYER_INFORMATION_V1: 'usageByGroupBuyerInformationV1',
  POP_CHATS_FROM_VA_V1: 'popChatsFromVaV1',
  POP_TICKETS_FROM_VA_V1: 'popTicketsFromVaV1',
  PSIS_TICKETS_FROM_VA_V1: 'psisTicketsFromVaV1',
  POP_AND_PSIS_CHATS_TICKETS_FROM_VA_V1: 'popAndPsisTicketsFromVaV1',
  POP_CHATS_FROM_ZENDESK_V1: 'popChatsFromZendeskV1',
  POP_TICKETS_FROM_ZENDESK_V1: 'popTicetsFromZendeskV1',
  PSIS_TICKETS_FROM_ZENDESK_V1: 'psisTicketsFromZendeskV1',
  POP_AND_PSIS_CHATS_AND_TICKETS_V1: 'popAndPsisChatsAndTicketsFromZendeskV1',
};
