/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
const ACA_ERROR_TYPE = {
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  SYSTEM_ERROR: 'SYSTEM_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INITIALIZATION_ERROR: 'INITIALIZATION_ERROR',
  BUSINESS_ERROR: 'BUSINESS_ERROR',
  AI_SERVICE_ERROR: 'AI_SERVICE_ERROR',
  UNDEFINED_ERROR: 'UNDEFINED_ERROR',
  QUERY_ERROR: 'QUERY_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR',
  HTTP_ERROR: 'HTTP_ERROR',
  JSON_RULE_ENGINE_ERROR: 'JSON_RULE_ENGINE_ERROR',
}


export {
  ACA_ERROR_TYPE,
}
