/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  CarbonModule,
  FadeModule,
  DownloadModule,
  EditModule,
  ManageProtectionModule,
  SysProvisionModule,
  CopyModule,
  ViewModule,
  ViewOffModule,
  DeleteModule,
  InformationModule,
  AddModule,
  WarningAltModule,
  WarningModule,
  ThumbsDownModule,
  ThumbsUpModule,
  FilterModule,
  PlayModule,
  ArrowUpRightModule,
  MaximizeModule,
  MinimizeModule,
  ResetModule,
  DocumentExportModule,
  DocumentImportModule, 
} from "@carbon/icons-angular";

import {
  ButtonModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InputModule,
  GridModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  TabsModule,
  StructuredListModule,
  TagModule,
  FileUploaderModule,
  PlaceholderModule,
  ProgressIndicatorModule,
  ComboBoxModule,
  AccordionModule,
  InlineLoadingModule,
  //
  LoadingModule,
  TilesModule,
  IconModule, 
} from 'carbon-components-angular';

@NgModule({
  imports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    DeleteModule,
    InformationModule,
    AddModule,
    WarningAltModule,
    WarningModule,
    ThumbsDownModule,
    ThumbsUpModule,
    FilterModule,
    PlayModule,
    ArrowUpRightModule,
    MaximizeModule,
    MinimizeModule,
    DocumentExportModule,
    DocumentImportModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    FileUploaderModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    ComboBoxModule,
    ResetModule,
    AccordionModule,
    InlineLoadingModule,
    //
    LoadingModule,
    TilesModule,
    IconModule, 
  ],
  exports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    DeleteModule,
    InformationModule,
    AddModule,
    WarningAltModule,
    WarningModule,
    ThumbsDownModule,
    ThumbsUpModule,
    FilterModule,
    PlayModule,
    ArrowUpRightModule,
    MaximizeModule,
    MinimizeModule,
    DocumentExportModule,
    DocumentImportModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    FileUploaderModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    ComboBoxModule,
    ResetModule,
    AccordionModule,
    InlineLoadingModule,
    //
    LoadingModule,
    TilesModule,
    IconModule, 
  ]
})
export class CarbonFrameworkModule { }
