/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  CarbonModule,
  FadeModule,
  DownloadModule,
  EditModule,
  ManageProtectionModule,
  SysProvisionModule,
  CopyModule,
  ViewModule,
  ViewOffModule,
  WarningModule,
  AddModule,
  ChevronLeftModule,
  ChevronRightModule,
  ThumbsUpModule,
  WarningAltModule,
  ThumbsDownModule,
  InformationModule,
  TrashCanModule,
  CheckmarkModule,
  CloudDownloadModule,
  ExportModule,
  CheckmarkFilledModule,
  ResetModule,
  DocumentImportModule,
} from "@carbon/icons-angular";

import {
  ButtonModule,
  BreadcrumbModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InputModule,
  GridModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  SliderModule,
  TabsModule,
  TilesModule,
  TagModule,
  IconModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    WarningModule,
    AddModule,
    ChevronLeftModule,
    ChevronRightModule,
    ThumbsUpModule,
    WarningAltModule,
    ThumbsDownModule,
    InformationModule,
    TrashCanModule,
    CheckmarkModule,
    CloudDownloadModule,
    ExportModule,
    CheckmarkFilledModule,
    DocumentImportModule,
    // -> carbon-components-angular
    ButtonModule,
    BreadcrumbModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SliderModule,
    SearchModule,
    TabsModule,
    TilesModule,
    TagModule,
    ResetModule,
    IconModule,
  ],
  exports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    WarningModule,
    AddModule,
    ChevronLeftModule,
    ChevronRightModule,
    ThumbsUpModule,
    WarningAltModule,
    ThumbsDownModule,
    InformationModule,
    TrashCanModule,
    CheckmarkModule,
    CloudDownloadModule,
    ExportModule,
    CheckmarkFilledModule,
    // -> carbon-components-angular
    ButtonModule,
    BreadcrumbModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SliderModule,
    SearchModule,
    TabsModule,
    TilesModule,
    TagModule,
    ResetModule,
    IconModule,
  ]
})
export class CarbonFrameworkModule {}
