/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
export const ANNOUNCEMENT_STATUSES = {
  PUBLISHED: 'PUBLISHED',
  REPUBLISHED: 'REPUBLISHED',
  ARCHIVED: 'ARCHIVED',
  READ: 'READ',
};

export const ANNOUNCEMENT_TYPE = 'ANNOUNCEMENT';

export const ANNOUNCEMENTS_ACTION_STATUSES = {
  NEEDS_ACTION: 'NEEDS ACTION',
  REMEDIATED: 'REMEDIATED',
  NO_ACTION: 'NO ACTION',
};
