/*
  © Copyright IBM Corporation 2022. All Rights Reserved 
   
  SPDX-License-Identifier: EPL-2.0
*/
import { NgModule } from '@angular/core';

import {
  CarbonModule,
  FadeModule,
  DownloadModule,
  EditModule,
  ManageProtectionModule,
  SysProvisionModule,
  CopyModule,
  ViewModule,
  ViewOffModule,
  DeleteModule,
  AddModule,
  BuildingModule,
  RuleModule,
  FilterModule,
  TrashCanModule,
  CheckmarkModule,
  CheckboxCheckedModule,
  InformationModule,
  CloudDownloadModule,
  ResetModule,
} from '@carbon/icons-angular';

import {
  ButtonModule,
  NotificationModule,
  DatePickerModule,
  DatePickerInputModule,
  DialogModule,
  DropdownModule,
  ModalModule,
  RadioModule,
  TableModule,
  PaginationModule,
  ToggleModule,
  InlineLoadingModule,
  InputModule,
  GridModule,
  ListModule,
  CheckboxModule,
  UIShellModule,
  SearchModule,
  TabsModule,
  StructuredListModule,
  TagModule,
  FileUploaderModule,
  PlaceholderModule,
  ProgressIndicatorModule,
  ComboBoxModule,
  AccordionModule,
  CodeSnippetModule,
  NumberModule,
} from 'carbon-components-angular';

@NgModule({
  imports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    DeleteModule,
    AddModule,
    BuildingModule,
    RuleModule,
    FilterModule,
    TrashCanModule,
    CheckmarkModule,
    CheckboxCheckedModule,
    InformationModule,
    CloudDownloadModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InlineLoadingModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    FileUploaderModule,
    ComboBoxModule,
    AccordionModule,
    CodeSnippetModule,
    NumberModule,
  ],
  exports: [
    // -> carbon-icons-angular
    CarbonModule,
    CopyModule,
    FadeModule,
    EditModule,
    SysProvisionModule,
    DownloadModule,
    ManageProtectionModule,
    ViewModule,
    ViewOffModule,
    DeleteModule,
    AddModule,
    BuildingModule,
    RuleModule,
    FilterModule,
    TrashCanModule,
    CheckmarkModule,
    CheckboxCheckedModule,
    InformationModule,
    CloudDownloadModule,
    // -> carbon-components-angular
    ButtonModule,
    NotificationModule,
    DatePickerModule,
    DatePickerInputModule,
    DialogModule,
    DropdownModule,
    ModalModule,
    RadioModule,
    TableModule,
    PaginationModule,
    ToggleModule,
    InlineLoadingModule,
    InputModule,
    GridModule,
    ListModule,
    CheckboxModule,
    UIShellModule,
    SearchModule,
    TabsModule,
    StructuredListModule,
    TagModule,
    PlaceholderModule,
    ProgressIndicatorModule,
    FileUploaderModule,
    ComboBoxModule,
    AccordionModule,
    CodeSnippetModule,
    NumberModule,
  ]
})
export class CarbonFrameworkModule {}
